### ISSUE TITLE
U2F timeouts over 60 secs are ignored (Chrome related)

### ISSUE THREAD

**Issue by faboweb** [cosmos/ledger-cosmos-js#8]
Setting a timeout for interactions doesn't work it stays with around 50s.

Snippet to reproduce:
```
import { App, comm_u2f } from "ledger-cosmos-js"
const communicationMethod = await comm_u2f.create_async(
        180,
        true
      )
const cosmosLedgerApp = new App(communicationMethod)
const response = await cosmosLedgerApp .sign(HDPATH, message)
```

**Comment by faboweb** [comment]
@jleni any progress on this? Users are reporting problems with this every day.

**Comment by jleni** [comment]
I will investigate today

**Comment by jleni** [comment]
The timeout is somehow capped at 60 secs by Chrome. 
I have update the library and tests to confirm the values passed are correct.
Any value below 60 is fine (within typical js variance), however, any value over 60 is limited to 60.

I believe this is definitely related to this issue here:
https://github.com/luniehq/lunie/issues/2077

I would recommend reopening to track Ledger / Google progress.
I will investigate a bit more to track where in Chrome things changed.

**Comment by jleni** [comment]
Additional logging shows that the timeout in the request to chrome's U2F transport is correct:

https://github.com/ZondaX/ledger-cosmos-js/blob/e8a30cab2223eb76e05dfbad3c9ede783d9ae237/src/chrome-u2f-api.js#L669

This test shows how any timeout over 60 is capped:
https://github.com/ZondaX/ledger-cosmos-js/blob/e8a30cab2223eb76e05dfbad3c9ede783d9ae237/tests/tests-browser.js#L44

**Comment by jleni** [comment]
I believe here is the culprit:

https://github.com/chromium/chromium/blob/5e78b515bc3dda4c969db56e3fd769bccc7d2fa4/third_party/blink/renderer/modules/credentialmanager/credential_manager_type_converters.cc#L29

**Comment by jleni** [comment]
Given that:
- This is something that is actually part of Chrome
- The recommendation is to move away from U2F in every platform and consider U2F obsolete.

I will close this issue. Please feel free to reopen if something substantial changes.
